name: Release DepScout

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        
      - name: Build for all platforms
        run: |
          # Build for Windows
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o depscout-${{ env.VERSION }}-windows-amd64.exe ./cmd/depscout/
          
          # Build for Linux
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o depscout-${{ env.VERSION }}-linux-amd64 ./cmd/depscout/
          
          # Build for macOS
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=${{ env.VERSION }}" -o depscout-${{ env.VERSION }}-darwin-amd64 ./cmd/depscout/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: DepScout v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            depscout-${{ env.VERSION }}-windows-amd64.exe
            depscout-${{ env.VERSION }}-linux-amd64
            depscout-${{ env.VERSION }}-darwin-amd64
          body: |
            # DepScout v${{ env.VERSION }} - Initial Release

            This is the first public release of **DepScout**, a high-performance, concurrent scanner for detecting Dependency Confusion vulnerabilities.

            ## Core Features
            - **Dependency Confusion Scanning**: Identifies potential Dependency Confusion vulnerabilities by scanning JavaScript files for package names and checking their existence on the public npm registry.
            - **Dual Parsing Engine**:
              - **Regex Mode**: Fast, high-performance scanning using fine-tuned regular expressions to find `require()` and `import` statements.
              - **Deep Scan Mode (`--deep-scan`)**: High-accuracy scanning using a full Abstract Syntax Tree (AST) parser to eliminate false positives from non-code contexts (e.g., comments). Includes an automatic fallback to regex if AST parsing fails.
            - **Concurrent Architecture**: Leverages a powerful, concurrent worker model to perform high-speed fetching and analysis of hundreds or thousands of files simultaneously.
            - **Adaptive Rate Limiting**: Features a smart, per-domain rate limiter that automatically adjusts request speeds based on server responses (e.g., `429 Too Many Requests`), maximizing speed without overwhelming targets.
            - **Flexible Input**: Accepts targets from single URLs (`-u`), files (`-f`), local directories (`-d`), or piped via `stdin`.
            - **Advanced Configuration**: Provides a rich set of CLI flags for fine-grained control.
            - **Multiple Output Formats**: Delivers results in human-readable text or machine-readable `JSON` (`--json`).

            ## Installation
            
            Download the appropriate binary for your platform and make it executable.
            
            For Go users:
            ```
            go install github.com/rafabd1/DepScout/cmd/depscout@latest
            ```
            
            ## Documentation
            
            See the [README.md](https://github.com/rafabd1/DepScout/blob/main/README.md) for usage details.